exclude: '.bumpversion.cfg$'
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: 'lib/pytest-lsp/pytest_lsp/clients/.*\.json'
  - id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black
    exclude: 'lib/pytest-lsp/pytest_lsp/gen.py'

- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args: [--config=lib/lsp-devtools/setup.cfg]

- repo: https://github.com/pycqa/isort
  rev: 5.13.0
  hooks:
  - id: isort
    name: isort (lsp-devtools)
    args: [--settings-file, lib/lsp-devtools/pyproject.toml]
    files: 'lib/lsp-devtools/lsp_devtools/.*\.py'

  - id: isort
    name: isort (pytest-lsp)
    args: [--settings-file, lib/pytest-lsp/pyproject.toml]
    files: 'lib/pytest-lsp/pytest_lsp/.*\.py'
    exclude: 'lib/pytest-lsp/pytest_lsp/gen.py'

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.7.1'
  hooks:
  - id: mypy
    name: mypy (pytest-lsp)
    args: [--explicit-package-bases,--check-untyped-defs]
    additional_dependencies:
    - importlib-resources
    - platformdirs
    - pygls
    - pytest
    - pytest-asyncio
    - websockets
    files: 'lib/pytest-lsp/pytest_lsp/.*\.py'

  - id: mypy
    name: mypy (lsp-devtools)
    args: [--explicit-package-bases,--check-untyped-defs]
    additional_dependencies:
    - aiosqlite
    - attrs
    - importlib-resources
    - platformdirs
    - pygls
    - stamina
    - textual
    - websockets
    files: 'lib/lsp-devtools/lsp_devtools/.*\.py'

- repo: local
  hooks:
  - id: check-capabilities
    name: check-capabilities
    language: python
    additional_dependencies:
    - lsprotocol
    files: 'lib/pytest-lsp/pytest_lsp/clients/.*\.json'
    entry: python scripts/check_capabilities.py
