name: lsp-devtools PR
on:
  pull_request:
    branches:
    - develop
    - release
    paths:
    - 'lib/lsp-devtools/**'

jobs:
  lsp-devtools:
    name: "Python v${{ matrix.python-version }} -- ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade build tox bump2version
      name: Setup Environment

    - run: |
        set -e

        # Despite the script's name, this is only used to obtain a
        # dev version number e.g. v1.2.3-dev4
        ./scripts/make-release.sh lsp-devtools
      name: Set Version
      if: matrix.python-version == '3.10'

    - run: |
        cd lib/lsp-devtools

        version=$(echo ${{ matrix.python-version }} | tr -d .)
        python -m tox -e `tox -l | grep $version | tr '\n' ','`
      name: Test

    - name: Package
      run: |
        cd lib/lsp-devtools
        python -m build
      if: always() && matrix.python-version == '3.10'

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: 'dist'
        path: lib/lsp-devtools/dist
      if: always() && matrix.python-version == '3.10'
