name: 'PR: lsp-devtools'
on:
  pull_request:
    branches:
    - develop
    - release
    paths:
    - 'lib/lsp-devtools/**'

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        python-version: "3.13"
        cache: pip
        cache-dependency-path: lib/lsp-devtools/pyproject.toml

    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade hatch towncrier
      name: Setup Environment

    - run: |
        set -e
        ./scripts/make_release.py lsp-devtools
      name: Set Version

    # TODO: https://github.com/hynek/build-and-inspect-python-package/tree/main#define-python-version-matrix-based-on-package-metadata
    - uses: hynek/build-and-inspect-python-package@2abe76da66d0a6a4a227101f9348ee855797cfa5 # v 3.0.1
      with:
        path: lib/lsp-devtools

  test:
    name: "Python v${{ matrix.python-version }} -- ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        allow-prereleases: true
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: lib/lsp-devtools/pyproject.toml

    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade hatch
      name: Setup Environment

    - run: |
        cd lib/lsp-devtools
        hatch test -i py=${{ matrix.python-version }}
      shell: bash
      name: Run Tests
