name: 'Release: lsp-devtools'

on:
  push:
    branches:
    - release
    paths:
    - 'lib/lsp-devtools/**'

jobs:
  release:
    name: lsp-devtools release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/lsp-devtools
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        python-version: "3.13"

    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install hatch towncrier docutils
      name: Install Build Tools

    - run: |
        set -e

        ./scripts/make_release.py lsp-devtools
      name: Set Version
      id: info

    - name: Package
      run: |
        cd lib/lsp-devtools
        hatch build

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: 'dist'
        path: lib/lsp-devtools/dist

    - name: Publish
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b  # v1.14.0
      with:
        packages-dir: lib/lsp-devtools/dist/

    - name: Create Release
      run: |
        gh release create "${RELEASE_TAG}" \
          --title "lsp-devtools v${VERSION} - ${RELEASE_DATE}" \
          -F lib/lsp-devtools/.changes.html \
          ./lib/lsp-devtools/dist/*
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
